### ISSUE TITLE
Error setting up entry for hifiberry due to `AttributeError`

### ISSUE THREAD

**Issue by jacobwod** [willholdoway/hifiberry#27]
As of yesterday the integration fails to initiate and I'm seeing this in the log:

```
2023-05-05 13:48:40.837 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.1.110 for hifiberry
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hifiberry/__init__.py", line 31, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

I verified that nothing has changed on the HifiBerry itself, the OS version is on `20230404`. 

I also verified that `/etc/audiocontrol2.conf` hasn't changed and that it still has the relevant lines:
```
[webserver]
enable = yes
port = 81
authtoken={foobar}
socketio_enabled=True
```

The device plays fine and shows up in Roon as an endpoint as usual. The Roon HA integration also sees the device, so that part is fine. But the "standard" `media_player` entity provided by this integration is missing, as it fails to initiate. 

Anyone else seeing this? Any ideas what I can check?

**Comment by jacobwod** [comment]
OK, I saw the PR #26 now…
